20230408_AsyncProgramming_CRUD/Controllers/PageController.cs
using _20230408_AsyncProgramming_CRUD.Infrastructure.Extensions.Classes;
using _20230408_AsyncProgramming_CRUD.Infrastructure.Extensions.Enums;
using _20230408_AsyncProgramming_CRUD.Infrastructure.Repositories.Interfaces;
using _20230408_AsyncProgramming_CRUD.Models.DTOs;
using _20230408_AsyncProgramming_CRUD.Models.Entities.Abstract;
using _20230408_AsyncProgramming_CRUD.Models.Entities.Concrete;
using _20230408_AsyncProgramming_CRUD.Models.VMs;
using AutoMapper;
using Microsoft.AspNetCore.Mvc;
using Microsoft.AspNetCore.Mvc.RazorPages;
using System;
using System.Linq;
using System.Net;
using System.Threading.Tasks;

namespace _20230408_AsyncProgramming_CRUD.Controllers
{
    public class PageController : Controller
    {
        private readonly IPageRepository _pageRepository;
        private readonly IMapper _mapper;

        public PageController(IPageRepository pageRepository, IMapper mapper)
        {
            this._pageRepository = pageRepository;
            this._mapper = mapper;
        }

        //public IActionResult Create()
        //{
        //    return View();
        //}
        public IActionResult Create() => View();


        [HttpPost]
        public async Task<IActionResult> Create(CreatePageDTO model)
        {
            if (ModelState.IsValid) // Parametre olarak gelen model içerisindeki model üyelere koyulan kurallara uyuldu mu ?
            {
                // Veri tabanındaki page tablosuna sadece "page" tipinde veri ekleyebiliriz. Bu action metoduna gelen veri tipi "CreatePageDTO" olduğundan direkt veri tabanındaki tabloya ekleyemeyiz. Bu yüzden DTO'dan gelen veriyi AutoMapper 3rd aracı ile Page varlığında üyeleri eşitliyoruz.
                var page = _mapper.Map<Models.Entities.Concrete.Page>(model);

                // Kullanıcıdan gelen data model ile buraya taşındı ve Page tipindeki page objesi ile dolduruldu. Artık oluşturulan repository ile veri tabanına ekleme işlemini gerçekleştirebiliriz.

                await _pageRepository.Add(page);
                TempData["Message"] = ExAlert.Create("The page has been created.", AlertType.success);
                return RedirectToAction("List");
            }

            TempData["Message"] = ExAlert.Create("The page hasn't been created.", AlertType.danger);
            return View(model);
        }

        public async Task<IActionResult> List()
        {
            var pages = await _pageRepository.GetFilteredList(
                 select: s => new PageVM
                 {
                     Id = s.Id,
                     Content = s.Content,
                     Status = s.Status,
                     Title = s.Title
                 },
                where: w => w.Status != Status.Passive,
                orderBy: o => o.OrderBy(x => x.Id)

                );

            return View(pages);
        }

        public async Task<IActionResult> Delete(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult((int)HttpStatusCode.BadRequest);
            }
            var page = await _pageRepository.GetById(id);
            if (page == null)
            {
                return NotFound();
            }
            var delete = await _pageRepository.Delete(page);
            if (delete)
                TempData["Message"] = ExAlert.Create("The page has been deleted.", AlertType.success);
            else
                TempData["Message"] = ExAlert.Create("The page hasn't been deleted.", AlertType.danger);
            return RedirectToAction("List");

        }

        public async Task<IActionResult> Edit(int? id)
        {
            if (id == null)
            {
                return new StatusCodeResult((int)HttpStatusCode.BadRequest);
            }
            var page = await _pageRepository.GetById(id);
            if (page == null)
            {
                return NotFound();
            }
            var model = _mapper.Map<UpdatePageDTO>(page);

            return View(model);
        }
        [HttpPost]
        public async Task<IActionResult> Edit(UpdatePageDTO model)
        {
            if (ModelState.IsValid)
            {
                var page = _mapper.Map<Models.Entities.Concrete.Page>(model);
                await _pageRepository.Update(page);
                TempData["Message"] = ExAlert.Create("The page has been updated", AlertType.success);
                return RedirectToAction("List");
            }
            else
            {
                TempData["Message"] = ExAlert.Create("The page hasn't been updated", AlertType.danger);
            }

            return View(model);
        }

    }
}

20230408_AsyncProgramming_CRUD/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8" />
    <meta name="viewport" content="width=device-width, initial-scale=1.0" />
    <title>@ViewData["Title"] - Async Programming</title>
    <link rel="stylesheet" href="~/lib/bootstrap/dist/css/bootstrap.min.css" />
    <link rel="stylesheet" href="~/css/site.css" />
</head>
<body>
    <header>
        <nav class="navbar navbar-expand-sm navbar-toggleable-sm navbar-light bg-white border-bottom box-shadow mb-3">
            <div class="container">
                <a class="navbar-brand" asp-area="" asp-controller="Home" asp-action="Index">_20230408_AsyncProgramming_CRUD</a>
                <button class="navbar-toggler" type="button" data-toggle="collapse" data-target=".navbar-collapse" aria-controls="navbarSupportedContent"
                        aria-expanded="false" aria-label="Toggle navigation">
                    <span class="navbar-toggler-icon"></span>
                </button>
                <div class="navbar-collapse collapse d-sm-inline-flex flex-sm-row-reverse">
                    <ul class="navbar-nav flex-grow-1">
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Page" asp-action="List">Pages</a>
                        </li>
                        <li class="nav-item">
                            <a class="nav-link text-dark" asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
                        </li>
                    </ul>
                </div>
            </div>
        </nav>
    </header>
    <div class="container">
        <main role="main" class="pb-3">
            <partial name="_NotificationPartial" />
            @RenderBody()
        </main>
    </div>

    <footer class="border-top footer text-muted">
        <div class="container">
            &copy; 2023 - Cmunlu - <a asp-area="" asp-controller="Home" asp-action="Privacy">Privacy</a>
        </div>
    </footer>
    <script src="~/lib/jquery/dist/jquery.min.js"></script>
    <script src="~/lib/bootstrap/dist/js/bootstrap.bundle.min.js"></script>
    <script src="~/js/site.js" asp-append-version="true"></script>
    @RenderSection("Scripts", required: false)
</body>
</html>

20230408_AsyncProgramming_CRUD/Views/Shared/_NotificationPartial.cshtml
@if(TempData["Message"] != null){
    <div class="notification">
        @Html.Raw(TempData["Message"])
    </div>
}